version: '3'

services:
  postgres:
    image: postgres:11
    container_name: full-stack-postgres
    ports: ['5432:5432']
    volumes:
      - ./db/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
